# .streamlit/secrets.toml

[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1xiBRf0dPlnhmpYKJrOAtdSLX5oBKfI0s6pvY3S1MVDw/edit#gid=0"

# From your JSON key file
type = "service_account"
project_id = "streamlitdivisioni"
private_key_id = "0805fa39dbc76adc34a9b404db447868d0f0f322"
private_key = '''
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC3tscFOPxkB6/P
4jQ43Vv/dGIawKGXxRiG0UJKxSRUdHxm+5ZgdIFfIUSLAQK9/bSZdZqtiW4LsNAo
DuLvQIRumVlX2i9uEVM+rWkJLh47z2nJNhNOGwNh8WFEKyDjBx71KngSmNmsUbld
IlHGUHI/fVlnN/2rr6hpPFObpwSKOYmGT6QLHgl+UPQ9Ib+tM6DpgnykFlnUYEsQ
ddOYDB6DQonHP/lLsK60iOgpFtmiUgpPqfv/I5kIUnPTygLAV2pkRVNwcG7Dgw6B
l4oukOnLTb9hIrat/VComhm93PSJFCrctkF543jvbROC5d/kbpyugf7oVRZmfr9t
OHl9sh5jAgMBAAECggEAFou2VKQ/3oYjo+dWpwHiLUawVtMmzFQ9DyfgMwKK/lhb
VLIcgX2FdlIZXNZvaoyXsjDrc3pHCI/sQ8uWkGvCX5EElL0AjslOhjB25aWvbSym
XAdTCttS03LG5TxGaXDcHOoCLq9ry0jY7vPsGuKQMCLR1X0wGEv9kYinRBYU/wzH
gGb2P5ElWq741b6zc/Bpxz4cc3hUV/cVAKJFZbLKRh6yWmc3nnj1q1MmQ5l4Bnyc
tW6XWdIOZfMYyeZYn2ZYuwUk4zjqS8ZghU4HBLfS3j9BWzyCmIjQFng8WIny3hNS
GuNwKTSZTzAwpvMMuGryUU2WoA6gGA/2eN0rVqt1zQKBgQDtXafpJr+psJSNrQ3B
6Jgtxs/HV39vbLnL1RricHw+mjo2BbXniBUqCFNpnFrcjrvwd3KpBYIprUPKD8AE
fhwEPXMHRV7BhL8Hx3NKWdWpSM0a0kx+Bi3wV801euYrt5MK6iCY24LZhmw895+2
AFhXi1LnTQchsMNIFRnO8hRw/wKBgQDGIuEZG1CvSZyQrq5bwveKrd2ml2FN/YGj
rjLBlLXVEeMApq78VjTr9LebA2y6nMnlukFDCV+P3+4VUsZFDkgl3uluEiyKUnO+
H5S4L80IB/9Ep9vt8IBJVLtLtwK1JZ0F4hRgPoZmDKey+FTqotIH02KH9d93HszH
xxw++iUunQKBgQDjzADr6YsA3/0BJnZQhNce/3DCXz9mgNKiQqclb0xdjAeXds2H
IPsmtozOiwZMKxNEiG3atfWf569qCMl/xkM+8nYlITb5w1rNrWUAksxRRRPJzM8q
FuYZhTnkPEkO5YNRczXLXMbr2Wyg6gg1U4l0ornyTuMsOwZ+c/mruHlTowKBgDcx
YCLuSPuLNeHXxxoopWwsIqJVaPWguIwv6lOiaUSBRwrXY8dG/Fb+RGcZ/R++rT8h
MyzJX6Vka53lAPYblF14Su4ugdnGPheoFHV6W1LxZ1poqAsQA6xpvgLJaCet4p/Q
6nwk7qteuxhPtNfnozoq2DendihonALKpEOmytTBAoGANwcnlSgxxYun6W9mHFUD
cbp5IK5v40mORNR6Xab58nc3FitVOCf47leF0LXLJjB6LujPN2zSyk0FW4IrMuui
4fgEuILL4s8tzu3c1xCQReXcM1bssJTngC73KMsugR0Bg19JSk2aKRXwDq8LQObR
wF+llftqwuR1Tck3lZdCRmY=
-----END PRIVATE KEY-----
'''
client_email = "divisione@streamlitdivisioni.iam.gserviceaccount.com"
client_id = "116678136247034327255"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/divisione%40streamlitdivisioni.iam.gserviceaccount.com"
